name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
      - name: Clean npm cache
        run: npm cache clean --force
      - name: List files
        run: ls -la
      - name: Check Cypress version
        run: npx cypress --version
      - name: Run Cypress tests
        run: npx cypress run --config-file=cypress.config.js    
      

