name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Install dependencies for headless browser
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgbm-dev \
          libnss3 \
          libatk1.0-0 \
          libx11-xcb1 \
          libdrm2 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libxi6 \
          libxss1 \
          libasound2 \
          libpangocairo-1.0-0

    - name: Start application
      run: npm start &
      env:
        CI: true

    - name: Wait for server to be ready
      run: npx wait-on http://localhost:3000

    - name: Run Cypress tests
      run: npx cypress run --config-file=cypress.config.js