name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start &
      env:
        CI: true
    
    - name: Instalando pacote wait
      run: npm install wait-on --save-dev

    - name: Run Cypress tests
      run: npx cypress run --config-file=cypress.config.js
    
    - name: Install Cypress
      run: npm install -g cypress

