name: End-to-end tests 🧪

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Passo 2: Limpar o cache npm para garantir uma instalação limpa
      - name: Clean npm cache
        run: npm cache clean --force

      # Passo 3: Instalar dependências com npm ci
      - name: Install dependencies
        run: npm ci

      # Passo 4: Verificar a versão do Cypress para garantir que está correto
      - name: Check Cypress version
        run: npx cypress --version

      # Passo 5: Listar arquivos para garantir que o `cypress.config.js` está presente
      - name: List files
        run: ls -la

      # Passo 6: Iniciar o servidor da aplicação
      - name: Start application
        run: npm start &
        # Certifique-se de que o seu comando `npm start` esteja correto, ou substitua por outro comando adequado para iniciar o servidor.

      # Passo 7: Esperar até que o servidor esteja acessível
      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3000 --timeout 300000

      # Passo 8: Executar os testes Cypress
      - name: Run Cypress tests
        run: npx cypress run --config-file=cypress.config.js