name: End-to-end tests 🧪

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Serve application
        run: npx serve -s build -l 3000 &
        env:
          CI: true

      - name: Start application
        run: npm start &

      - name: Wait for application
        run: npx wait-on http://localhost:3000 --timeout 300000

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true
